# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c902f0bc45759156ed6557f168fdb299800f8a5787cdfeb1384a86d7419472dd9f1826b7bddf530786fe677b36c6be85f8bd600d2e19aeb570a94d1ebd3ccfc8

test:
  secret_key_base: 8a35444f0c11bfd9ab6a50e52c2a76b76cf646ac71147557a0a54c9121f5e236d3ee25ea878caa0dc5f528a2abd8393224aa8971656dfa376e4ea4f22d3c7569

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
